const en = {
  nav: {
    anasayfa: "Home",
    urunler: "Products",
    hakkimizda: "About",
    haberler: "News",
    bayilik: "Become a dealer",
    iletisim: "Contact",
    teklif: "Get a quote",
    menu: "Menu",
    dil: "Language",
    atla: "Skip to content",
  },

  alt: {
    cagriUst: "Wholesale orders",
    cagri1: "Put",
    cagriVurgu: "Mr ResBaa",
    cagri2: "on your shelves.",
    fiyatListesi: "Request price list",
    bayiOlun: "Become a dealer",
    tanitim: "Dragée, chocolate and confectionery made in Şuhut, Afyonkarahisar. Halal certified, exported to {ulke} countries.",
    kesfet: "Explore",
    iletisim: "Contact",
    bayilikBasvuru: "Dealer application",
    katalog: "Product catalogue (PDF)",
    haklar: "All rights reserved.",
    kvkk: "Privacy notice",
    gizlilik: "Privacy",
    cerezler: "Cookies",
    vd: "Tax office",
    vn: "Tax no",
    mersis: "MERSIS",
  },

  wa: {
    aria: "Message us on WhatsApp",
    bilgi: "Hello, I would like information about your wholesale products.",
    fiyatListesi: "Hello, I would like to receive your wholesale price list.",
    fiyatListesi2: "Hello, could you please send me the current wholesale price list?",
    bilgiKisa: "Hello, I would like some information.",
    urun: "Hello, I would like a wholesale price for {ad} ({gramaj}).",
  },

  kat: { draje: "Dragée", krema: "Spreads & Chocolate" },
  haberKat: { basin: "In the Press", ihracat: "Export", fabrika: "Factory & Production", urun: "Product News" },

  meta: {
    ana: {
      baslik: "MB Çikolata | Wholesale Dragée, Chocolate & Confectionery – Türkiye",
      aciklama:
        "MB Çikolata makes Mr ResBaa halal certified chocolate-coated dragées and chocolate products in Afyonkarahisar, Türkiye, and sells wholesale. Exporting to {ulke} countries. Get in touch for a quote.",
    },
    urunler: {
      baslik: "Products – Wholesale Dragée & Chocolate",
      aciklama:
        "Twelve varieties of Mr ResBaa chocolate-coated dragée, cocoa hazelnut spread and crispy potato chocolate. Halal certified, wholesale.",
    },
    hakkimizda: {
      baslik: "About Us – Resul Baskı's Story and Our Şuhut Plant",
      aciklama:
        "MB Çikolata grew out of Resul Baskı's story, which began as a worker in a chocolate factory. Today it produces in a 2,000 m² plant in Şuhut OSB and exports to {ulke} countries.",
    },
    haberler: { baslik: "News", aciklama: "Latest news from MB Çikolata: trade fairs, the new plant, exports and new products." },
    iletisim: {
      baslik: "Contact – Wholesale Orders & Quotes",
      aciklama:
        "Contact MB Çikolata: Şuhut OSB, Afyonkarahisar, Türkiye. Phone {telefon}, email {eposta}. Fill in the form for a wholesale quote.",
    },
    bayilik: {
      baslik: "Dealer Application",
      aciklama:
        "Become an MB Çikolata dealer and sell Mr ResBaa dragées and chocolate in your region. Fill in the application form and we will get back to you.",
    },
    urunAciklamaSonu: "Contact MB Çikolata for a wholesale price.",
    urunBaslik: "Mr ResBaa {ad} {gramaj} – Wholesale",
    yonetim: "Admin Panel",
  },

  ana: {
    eyebrow: "Afyonkarahisar · {tecrube} years of craft",
    h1a: "Sweet moments",
    h1vurgu: "taste better",
    h1b: "with chocolate.",
    altYazi:
      "From hazelnut to pistachio, from freeze-dried fruit to coffee beans: we make our halal certified dragées in our own plant and ship them to {ulke} countries.",
    btnUrun: "Explore products",
    btnFiyat: "Get wholesale prices",
    rozet: "MB ÇİKOLATA · HALAL CERTIFIED · WHOLESALE · AFYONKARAHISAR · ",
    videoAria: "Melted chocolate, MB Chocolate",
    paketAlt: "{ad} pack",
    asagi: "Scroll down",
    seritAria: "Our flavours",
    lezzetler: ["Hazelnut", "Pistachio", "Almond", "Mango", "Strawberry", "Sour cherry", "Blackberry", "Coffee bean", "Biscuit", "BinBonBon", "Chocolate stones"],

    tanitimUst: "For flavour lovers",
    tanitimBas1: "Mb Çikolata makes",
    tanitimVurgu: "one-of-a-kind",
    tanitimBas2: "flavours.",
    tanitimYazi:
      "Download our catalogue to take a closer look at our flavours and product range. For wholesale orders, mixes, case contents and shipping, just write to us.",
    katalog: "Online catalogue (PDF)",
    kutuAlt: "MB Çikolata gift box of chocolates",
    ozellikler: [
      { baslik: "Natural products", yazi: "We care about naturalness in everything we use. Our fruit is freeze-dried." },
      { baslik: "Careful packaging", yazi: "Our products are made without hand contact and reach you in resealable zip-lock pouches, packed under hygienic conditions." },
      { baslik: "Quality cocoa", yazi: "We make halal certified recipes with no added glucose syrup, using quality cocoa." },
    ],

    bildiri1: "At Mb Çikolata we offer",
    bildiriVurgu: "delicious",
    bildiri2: "products.",

    urunUst: "The Mr ResBaa series",
    urunBaslik: "Discover our flavours",
    urunYazi: "Twelve milk and white chocolate-coated dragées, cocoa hazelnut spread and crispy potato chocolate.",
    tumUrunler: "All products ({n})",

    mektupUst: "Hello",
    mektupAlt: "A strawberry dipped in melted chocolate",
    mektup1: "On this road we set out on with a love of chocolate, we offer flavour-filled products made with the finest ingredients and carefully selected cocoa beans.",
    mektup2:
      "My journey began on the production line of a chocolate factory in Istanbul. Today, in my home province Afyonkarahisar, our team of 30 produces in our plant in Şuhut and we send our products all over Türkiye and to {ulke} countries.",
    mektup3: "MB Çikolata is not just a chocolate brand; it is a symbol of love and passion. We invite you to join this journey of flavour.",
    imzaNot: "With warm wishes and lots of chocolate,",
    imzaAd: "Resul Baskı",
    imzaUnvan: "Founder",

    tesisUst: "Şuhut OSB",
    tesisBaslik: "We produce in our own plant",
    tesisYazi: "In the plant we built with TKDK support, we raised our capacity by 150 percent. We can ship regularly to both the domestic market and export markets.",
    tesisLink: "Read our story",
    tesisBilgi: [
      ["2,000 m²", "indoor production area"],
      ["150%", "capacity increase"],
      ["30", "people on the team"],
      ["Halal", "certified production"],
    ],

    haberUst: "News",
    haberBaslik: "From MB Çikolata",
    haberTum: "All news",
  },

  urunlerSayfa: {
    ust: "The Mr ResBaa series",
    baslik: "Our products",
    yazi: "Everything is made in our plant in Afyonkarahisar. Write to us for wholesale prices and minimum order quantities.",
    tumu: "All",
    cagriBaslik: "Would you like our price list?",
    cagriYazi: "We will send you the current wholesale prices on WhatsApp right away.",
    cagriWa: "Write on WhatsApp",
    cagriForm: "Fill in the form",
    incele: "View",
  },

  urunDetay: {
    kirintiAna: "Home",
    kirintiAria: "Breadcrumb",
    marka: "Brand",
    ambalaj: "Packaging",
    ambalajDeger: "80 g zip-lock",
    helal: "Halal certificate",
    var: "Yes",
    glikoz: "Added glucose syrup",
    yok: "None",
    satis: "Sales",
    toptan: "Wholesale",
    netMiktar: "Net quantity",
    teklif: "Get a quote for this product",
    ara: "Call: {tel}",
    benzer: "You may also like",
    resimAlt: "Mr ResBaa {ad} {gramaj} pack",
  },

  hakkimizda: {
    ust: "Our story",
    baslik: "About us",
    yazi: "A story that began on a production line and now sends chocolate to {ulke} countries.",
    hBaslik: "Our story",
    h1: "MB Çikolata's founder Resul Baskı entered the industry as a worker at a chocolate factory in Istanbul. Working on the production line and in packaging, he learned every stage of the job first-hand, and later bought the factory he worked in.",
    h2: "He then moved his investment to his home province, Afyonkarahisar. With a non-repayable grant of about 6.76 million TL from TKDK, he built a 2,000 m² plant in the Şuhut Organized Industrial Zone. The project became one of TKDK's first in Afyonkarahisar.",
    h3: "Today 30 people work at the plant and capacity is up by 150 percent. Our products go to dealers in Türkiye and abroad.",
    fotoAlt: "Resul Baskı's story",
    kutular: [
      {
        baslik: "What we make and how",
        yazi: "Under the Mr ResBaa brand we make 12 kinds of dragée: hazelnut, pistachio, almond, coffee bean, biscuit, freeze-dried strawberry, cherry and mango, blackberry, BinBonBon and chocolate stones. We also make a cocoa hazelnut spread and a crispy potato chocolate.",
      },
      {
        baslik: "Our standards",
        yazi: "Our products are halal certified and our dragées contain no added glucose syrup. Every product is packed in an 80 g zip-lock pouch that suits shelves and wholesale.",
      },
      {
        baslik: "Our goal",
        yazi: "“We have opened up to Europe and we will keep expanding with new products.” We keep growing our range and our export markets.",
      },
    ],
    ihracatBaslik: "Our main export markets",
    ulkeler: ["Iraq", "Iran", "Indonesia", "Venezuela", "Germany", "Saudi Arabia", "Libya"],
    ihracatYazi: "We export to {ulke} countries in total, including shipments to various European markets.",
    cagriBaslik: "Let's work together",
    cagriYazi: "Talk to us about wholesale, dealerships or export.",
    cagriBayi: "Dealer application",
    cagriIletisim: "Contact",
  },

  haberlerSayfa: {
    ust: "From MB Çikolata",
    baslik: "News",
    yazi: "Trade fairs, investments, exports and new products.",
    tumu: "All news",
    kirintiAria: "Breadcrumb",
    anasayfa: "Home",
  },

  iletisimSayfa: {
    ust: "Wholesale orders",
    baslik: "Contact",
    yazi: "Get in touch for wholesale prices, samples and orders.",
    fabrika: "Factory",
    telefon: "Phone",
    eposta: "Email",
    saatler: "Opening hours",
    wa: "Write on WhatsApp",
    teklif: "Request a quote",
    harita: "MB Çikolata factory location",
  },

  bayilikSayfa: {
    ust: "Work with us",
    baslik: "Dealer application",
    yazi: "Whether you run a supermarket, confectioner, nut shop or distribution business, put Mr ResBaa on your shelves.",
    hBaslik: "Working with us",
    liste: [
      "12 kinds of halal certified dragée in the Mr ResBaa series",
      "80 g zip-lock pouches, ready for retail shelves",
      "Wholesale prices straight from the producer",
      "Shipping across Türkiye and abroad",
    ],
    p1: "Minimum order quantities and prices vary by region and product. Fill in the form and we will get back to you with the details.",
    p2a: "If you would like to see the product catalogue first, you can",
    p2link: "download it here",
    form: "Application form",
  },

  form: {
    adSoyad: "Full name",
    telefon: "Phone",
    telefonIpucu: "+90 5xx xxx xx xx",
    firma: "Company",
    varsa: "(optional)",
    sehir: "City",
    isletme: "Business type",
    sec: "Select",
    isletmeler: ["Supermarket / grocery", "Nut shop / confectioner", "Wholesaler / distributor", "Café / restaurant", "Online seller", "Other"],
    mesaj: "Your message",
    mesajIpucuTeklif: "Which products are you interested in, and roughly how much?",
    mesajIpucuBayi: "Tell us briefly about your region and your needs.",
    not: "When you press Send, WhatsApp opens with your message ready. Your details are only used to get back to you; see the [privacy notice](/kvkk) for details.",
    hata: "Please enter your name and a valid phone number.",
    gonder: "Send via WhatsApp",
    epostaYaz: "Write an email",
    msgTeklif: "Hello, I would like to receive a wholesale price quote.",
    msgBayi: "Hello, I would like to apply to become a dealer.",
    msgAd: "Name",
    msgFirma: "Company",
    msgSehir: "City",
    msgIsletme: "Business type",
    msgTelefon: "Phone",
    msgMesaj: "Message",
  },

  yasal: {
    ust: "Legal",
    guncelleme: "Last updated",
    tarih: "October 2026",
    not: "This is a convenience translation. In case of any difference, the Turkish version prevails.",
    kvkk: {
      baslik: "Privacy Notice (KVKK)",
      blok: [
        ["p", "Under Article 10 of Turkish Personal Data Protection Law no. 6698 (KVKK), this notice explains how your personal data is processed."],
        ["h", "Data controller"],
        ["p", "{unvan}, {adres}. Email: {eposta}"],
        ["h", "What data we collect"],
        ["p", "The name, phone number, company name, city, business type and message you enter in the contact and dealer forms. We do not collect any other data that identifies you on this site."],
        ["h", "What we use it for"],
        ["p", "To give you a price quote, assess your dealer application, answer your questions and carry out the order process. Your data is not added to any marketing list."],
        ["h", "Legal basis"],
        ["p", "Processing is necessary to handle your request and to hold preliminary discussions for a contract (KVKK Art. 5/2-c), and for our legitimate interests (Art. 5/2-f)."],
        ["h", "Who we share it with"],
        ["p", "The forms open WhatsApp with your message ready; if you send it, the content reaches us through the WhatsApp infrastructure. If you write by email, your message is kept with our email provider. We do not share it with third parties except where required by law."],
        ["h", "How long we keep it"],
        ["p", "After the conversation ends, until the statutory retention periods expire; it is then deleted or anonymised."],
        ["h", "Your rights"],
        ["p", "Under KVKK Art. 11 you have the right to learn whether your data is processed, request information if it is, learn whether it is used for its purpose, ask for correction if it is incomplete or wrong, ask for deletion or destruction when the conditions are met, and claim compensation if you suffer harm from unlawful processing."],
        ["p", "You can write to {eposta} with your requests; we reply within 30 days at the latest."],
      ],
    },
    gizlilik: {
      baslik: "Privacy Policy",
      blok: [
        ["p", "This site was made to present {ad} products and receive wholesale enquiries. We respect the privacy of our visitors."],
        ["h", "Information we collect"],
        ["p", "There are no accounts, shopping carts or online payments on this site. We only receive the information you type if you fill in and send a form. How it is processed is explained in the [privacy notice (KVKK)](/kvkk)."],
        ["h", "Tracking and ads"],
        ["p", "We do not use any advertising or user-tracking tools on this site. If we add an analytics tool in the future, we will update this page and the [cookie policy](/cerez-politikasi)."],
        ["h", "Third-party services"],
        ["p", "Google Maps is embedded on the contact page; when the map loads, Google may process data under its own policy. When you click WhatsApp or social media links, the rules of that platform apply."],
        ["h", "Contact"],
        ["p", "For any questions you can write to {eposta}."],
      ],
    },
    cerez: {
      baslik: "Cookie Policy",
      blok: [
        ["p", "This site does not set any cookies of its own: we use no session, analytics or advertising cookies, so we do not show a consent banner."],
        ["h", "Exception: the embedded map"],
        ["p", "When the Google Maps component on the contact page loads, Google may set its own cookies. If you do not want that, you can block third-party cookies in your browser, or reach us by phone and email without opening that page."],
        ["h", "In the future"],
        ["p", "If we add a tool that uses cookies, for example to count visitors, we will ask for your consent first and update this page."],
      ],
    },
  },

  bulunamadi: {
    baslik: "We couldn't find this page",
    yazi: "The address may have changed or been mistyped.",
    ana: "Back to home",
    urunler: "See products",
  },
};

export default en;
