// Arayüz metinleri. Aynı anahtarlar en.js ve ar.js içinde de var.
// {ulke}, {tecrube} gibi parçalar data/ayarlar.json'daki rakamlardan doldurulur.
const tr = {
  nav: {
    anasayfa: "Anasayfa",
    urunler: "Ürünler",
    hakkimizda: "Hakkımızda",
    haberler: "Haberler",
    bayilik: "Bayilik",
    iletisim: "İletişim",
    teklif: "Teklif İste",
    menu: "Menü",
    dil: "Dil",
    atla: "İçeriğe geç",
  },

  alt: {
    cagriUst: "Toptan sipariş",
    cagri1: "Rafınıza",
    cagriVurgu: "Mr ResBaa",
    cagri2: "ekleyin.",
    fiyatListesi: "Fiyat listesi iste",
    bayiOlun: "Bayi olun",
    tanitim: "Afyonkarahisar Şuhut'ta üretilen draje, çikolata ve şekerleme. Helal sertifikalı, {ulke} ülkeye ihracat.",
    kesfet: "Keşfet",
    iletisim: "İletişim",
    bayilikBasvuru: "Bayilik başvurusu",
    katalog: "Ürün kataloğu (PDF)",
    haklar: "Tüm hakları saklıdır.",
    kvkk: "KVKK",
    gizlilik: "Gizlilik",
    cerezler: "Çerezler",
    vd: "V.D.",
    vn: "VN",
    mersis: "MERSİS",
  },

  wa: {
    aria: "WhatsApp'tan yazın",
    bilgi: "Merhaba, toptan ürünleriniz hakkında bilgi almak istiyorum.",
    fiyatListesi: "Merhaba, toptan fiyat listesi almak istiyorum.",
    fiyatListesi2: "Merhaba, güncel toptan fiyat listesini rica ediyorum.",
    bilgiKisa: "Merhaba, bilgi almak istiyorum.",
    urun: "Merhaba, {ad} ({gramaj}) için toptan fiyat almak istiyorum.",
  },

  kat: { draje: "Draje", krema: "Krema ve Çikolata" },
  haberKat: { basin: "Basında Biz", ihracat: "İhracat", fabrika: "Fabrika ve Üretim", urun: "Ürün Haberleri" },

  meta: {
    ana: {
      baslik: "MB Çikolata | Toptan Draje, Çikolata ve Şekerleme – Afyonkarahisar",
      aciklama:
        "Afyonkarahisar'da üretim yapan MB Çikolata, Mr ResBaa markalı 12 çeşit helal sertifikalı draje ve çikolata ürünlerini toptan satıyor. {ulke} ülkeye ihracat. Teklif için bize yazın.",
    },
    urunler: {
      baslik: "Ürünler – Toptan Draje ve Çikolata",
      aciklama:
        "Mr ResBaa markalı 12 çeşit çikolata kaplamalı draje, kakaolu fındık kreması ve çıtır patatesli çikolata. Helal sertifikalı, toptan satış.",
    },
    hakkimizda: {
      baslik: "Hakkımızda – Resul Baskı'nın Hikayesi ve Şuhut Tesisimiz",
      aciklama:
        "MB Çikolata, Resul Baskı'nın bir çikolata fabrikasında işçilikle başlayan hikayesinden doğdu. Bugün Şuhut OSB'deki 2.000 m² tesisinde üretim yapıyor ve {ulke} ülkeye ihracat gerçekleştiriyor.",
    },
    haberler: { baslik: "Haberler", aciklama: "MB Çikolata'dan son haberler: fuarlar, yeni tesis, ihracat ve yeni ürünler." },
    iletisim: {
      baslik: "İletişim – Toptan Sipariş ve Teklif",
      aciklama:
        "MB Çikolata iletişim: Şuhut OSB, Afyonkarahisar. Telefon {telefon}, e-posta {eposta}. Toptan fiyat teklifi için formu doldurun.",
    },
    bayilik: {
      baslik: "Bayilik Başvurusu",
      aciklama:
        "MB Çikolata bayisi olun: Mr ResBaa draje ve çikolata ürünlerini kendi bölgenizde satın. Başvuru formunu doldurun, size dönüş yapalım.",
    },
    urunAciklamaSonu: "MB Çikolata'dan toptan fiyat için bize yazın.",
    urunBaslik: "Mr ResBaa {ad} {gramaj} – Toptan",
    yonetim: "Yönetim Paneli",
  },

  ana: {
    eyebrow: "Afyonkarahisar · {tecrube} yıllık ustalık",
    h1a: "Tatlı anlar için",
    h1vurgu: "en lezzetli",
    h1b: "çikolatalar.",
    altYazi:
      "Fındıktan Antep fıstığına, dondurularak kurutulmuş meyveden kahve çekirdeğine; helal sertifikalı drajelerimizi kendi tesisimizde üretip {ulke} ülkeye gönderiyoruz.",
    btnUrun: "Ürünleri keşfet",
    btnFiyat: "Toptan fiyat al",
    rozet: "MB ÇİKOLATA · HELAL SERTİFİKALI · TOPTAN · AFYONKARAHİSAR · ",
    videoAria: "Erimiş çikolata, MB Chocolate",
    paketAlt: "{ad} paketi",
    asagi: "Aşağı kaydır",
    seritAria: "Lezzetlerimiz",
    lezzetler: ["Fındık", "Antep fıstığı", "Badem", "Mango", "Çilek", "Vişne", "Böğürtlen", "Kahve çekirdeği", "Bisküvi", "BinBonBon", "Çikolata taşları"],

    tanitimUst: "Lezzet tutkunları için",
    tanitimBas1: "Mb Çikolata,",
    tanitimVurgu: "eşsiz tatlar",
    tanitimBas2: "üretiyor.",
    tanitimYazi:
      "Lezzetlerimizi ve ürün çeşitlerimizi yakından incelemek için kataloğumuzu indirin. Toptan alımda ürün karması, koli içeriği ve sevkiyat için bize yazmanız yeterli.",
    katalog: "Online katalog (PDF)",
    kutuAlt: "MB Çikolata hediyelik çikolata kutusu",
    ozellikler: [
      { baslik: "Doğal ürünler", yazi: "Kullandığımız malzemelerde doğallığı önemsiyoruz. Meyveler dondurularak kurutuluyor." },
      { baslik: "Özenli paketleme", yazi: "Ürünlerimiz el değmeden üretilir, hijyenik koşullarda tekrar kapanabilen zip-lock ambalajla size ulaşır." },
      { baslik: "Kaliteli kakao", yazi: "Helal sertifikalı, ilave glikoz şurubu içermeyen tariflerle kaliteli kakaodan üretiyoruz." },
    ],

    bildiri1: "Mb Çikolata olarak",
    bildiriVurgu: "lezzetli",
    bildiri2: "ürünler sunuyoruz.",

    urunUst: "Mr ResBaa serisi",
    urunBaslik: "Lezzetlerimizi keşfedin",
    urunYazi: "Sütlü ve beyaz çikolata kaplı 12 draje, kakaolu fındık kreması ve çıtır patatesli çikolata.",
    tumUrunler: "Tüm ürünler ({n})",

    mektupUst: "Merhaba",
    mektupAlt: "Erimiş çikolataya batırılmış çilek",
    mektup1: "Çikolata sevgisiyle çıktığımız bu yolda, en kaliteli malzemeleri ve özenle seçilmiş kakao çekirdeklerini kullanarak lezzet dolu ürünler sunuyoruz.",
    mektup2:
      "Yolculuğum İstanbul'da bir çikolata fabrikasının üretim bandında başladı. Bugün memleketim Afyonkarahisar'da, Şuhut'taki tesisimizde 30 kişilik ekibimizle üretiyor, ürünlerimizi Türkiye'nin dört bir yanına ve {ulke} ülkeye gönderiyoruz.",
    mektup3: "MB Çikolata sadece bir çikolata markası değil; sevginin ve tutkunun simgesi. Sizi bu lezzet yolculuğuna davet ediyoruz.",
    imzaNot: "Sevgi ve çikolata dolu günler dilerim,",
    imzaAd: "Resul Baskı",
    imzaUnvan: "Kurucu",

    tesisUst: "Şuhut OSB",
    tesisBaslik: "Üretimi kendi tesisimizde yapıyoruz",
    tesisYazi: "TKDK desteğiyle kurduğumuz tesiste kapasitemizi yüzde 150 artırdık. Hem iç pazara hem ihracata düzenli sevkiyat yapabiliyoruz.",
    tesisLink: "Hikayemizi okuyun",
    tesisBilgi: [
      ["2.000 m²", "kapalı üretim alanı"],
      ["%150", "kapasite artışı"],
      ["30", "kişilik ekip"],
      ["Helal", "sertifikalı üretim"],
    ],

    haberUst: "Haberler",
    haberBaslik: "MB Çikolata'dan",
    haberTum: "Tüm haberler",
  },

  urunlerSayfa: {
    ust: "Mr ResBaa serisi",
    baslik: "Ürünlerimiz",
    yazi: "Hepsi Afyonkarahisar'daki tesisimizde üretiliyor. Toptan fiyat ve minimum sipariş için bize yazmanız yeterli.",
    tumu: "Tümü",
    cagriBaslik: "Fiyat listesi ister misiniz?",
    cagriYazi: "Güncel toptan fiyatları WhatsApp'tan hemen iletelim.",
    cagriWa: "WhatsApp'tan yaz",
    cagriForm: "Form doldur",
    incele: "İncele",
  },

  urunDetay: {
    kirintiAna: "Anasayfa",
    kirintiAria: "Konum",
    marka: "Marka",
    ambalaj: "Ambalaj",
    ambalajDeger: "80 gr zip-lock",
    helal: "Helal sertifikası",
    var: "Var",
    glikoz: "İlave glikoz şurubu",
    yok: "Yok",
    satis: "Satış",
    toptan: "Toptan",
    netMiktar: "Net miktar",
    teklif: "Bu ürün için teklif al",
    ara: "Ara: {tel}",
    benzer: "Bunlara da bakın",
    resimAlt: "Mr ResBaa {ad} {gramaj} ambalajı",
  },

  hakkimizda: {
    ust: "Hikayemiz",
    baslik: "Hakkımızda",
    yazi: "Bir üretim bandında başlayan, bugün {ulke} ülkeye çikolata gönderen hikaye.",
    hBaslik: "Hikayemiz",
    h1: "MB Çikolata'nın kurucusu Resul Baskı, sektöre İstanbul'da bir çikolata fabrikasında işçi olarak girdi. Üretim bandında, paketleme biriminde çalışarak işin her aşamasını yerinde öğrendi; sonra çalıştığı fabrikayı satın aldı.",
    h2: "Yatırımını memleketi Afyonkarahisar'a taşıdı. TKDK'dan aldığı yaklaşık 6,76 milyon TL'lik geri ödemesiz hibeyle Şuhut Organize Sanayi Bölgesi'nde 2.000 metrekarelik bir tesis kurdu. Bu proje TKDK'nın Afyonkarahisar'daki ilk projelerinden biri oldu.",
    h3: "Bugün tesiste 30 kişi çalışıyor, kapasite yüzde 150 arttı. Ürünler hem Türkiye'deki bayilere hem yurt dışına gidiyor.",
    fotoAlt: "Resul Baskı'nın hikayesi",
    kutular: [
      {
        baslik: "Neyi, nasıl üretiyoruz",
        yazi: "Mr ResBaa markasıyla 12 çeşit draje üretiyoruz: fındık, Antep fıstığı, badem, kahve çekirdeği, bisküvi, dondurularak kurutulmuş çilek, vişne ve mango, böğürtlen, BinBonBon ve çikolata taşları. Ayrıca kakaolu fındık kreması ve çıtır patatesli çikolata var.",
      },
      {
        baslik: "Standartlarımız",
        yazi: "Ürünlerimiz helal sertifikalı, drajelerimizde ilave glikoz şurubu kullanmıyoruz. Her ürün 80 gr zip-lock ambalajda, raf ve toptan satışa uygun şekilde paketleniyor.",
      },
      {
        baslik: "Hedefimiz",
        yazi: "“Avrupa'ya açıldık, yeni ürünlerle açılmaya devam edeceğiz.” Ürün gamını ve ihracat pazarlarını büyütmeye devam ediyoruz.",
      },
    ],
    ihracatBaslik: "Başlıca ihracat pazarlarımız",
    ulkeler: ["Irak", "İran", "Endonezya", "Venezuela", "Almanya", "Suudi Arabistan", "Libya"],
    ihracatYazi: "Toplam {ulke} ülkeye ihracat yapıyoruz; bunların yanında çeşitli Avrupa pazarlarına da sevkiyat var.",
    cagriBaslik: "Birlikte çalışalım",
    cagriYazi: "Toptan alım, bayilik ya da ihracat için bizimle konuşun.",
    cagriBayi: "Bayilik başvurusu",
    cagriIletisim: "İletişim",
  },

  haberlerSayfa: {
    ust: "MB Çikolata'dan",
    baslik: "Haberler",
    yazi: "Fuarlar, yatırımlar, ihracat ve yeni ürünler.",
    tumu: "Tüm haberler",
    kirintiAria: "Konum",
    anasayfa: "Anasayfa",
  },

  iletisimSayfa: {
    ust: "Toptan sipariş",
    baslik: "İletişim",
    yazi: "Toptan fiyat, numune ve sipariş için bize ulaşın.",
    fabrika: "Fabrika",
    telefon: "Telefon",
    eposta: "E-posta",
    saatler: "Çalışma saatleri",
    wa: "WhatsApp'tan yaz",
    teklif: "Teklif isteyin",
    harita: "MB Çikolata fabrika konumu",
  },

  bayilikSayfa: {
    ust: "Bizimle çalışın",
    baslik: "Bayilik başvurusu",
    yazi: "Market, şekerci, kuruyemişçi ya da distribütörseniz Mr ResBaa'yı rafınıza alın.",
    hBaslik: "Bizimle çalışmak",
    liste: [
      "Mr ResBaa serisinde 12 çeşit helal sertifikalı draje",
      "80 gr zip-lock ambalaj, raf satışına uygun",
      "Doğrudan üreticiden toptan fiyat",
      "Türkiye'nin her yerine sevkiyat",
    ],
    p1: "Minimum sipariş miktarı ve fiyatlar bölgeye ve ürün çeşidine göre değişiyor. Formu doldurun, size dönüş yapıp ayrıntıları anlatalım.",
    p2a: "Ürün kataloğunu önceden görmek isterseniz",
    p2link: "buradan indirebilirsiniz",
    form: "Başvuru formu",
  },

  form: {
    adSoyad: "Ad soyad",
    telefon: "Telefon",
    telefonIpucu: "05xx xxx xx xx",
    firma: "Firma",
    varsa: "(varsa)",
    sehir: "Şehir",
    isletme: "İşletme türü",
    sec: "Seçin",
    isletmeler: ["Market / bakkal", "Kuruyemişçi / şekerci", "Toptancı / distribütör", "Kafe / restoran", "Online satıcı", "Diğer"],
    mesaj: "Mesajınız",
    mesajIpucuTeklif: "Hangi ürünlerle ilgileniyorsunuz, yaklaşık ne kadar?",
    mesajIpucuBayi: "Bölgeniz ve ihtiyacınız hakkında kısaca yazın.",
    not: "Gönder'e basınca WhatsApp açılır ve mesajınız hazır gelir. Bilgileriniz yalnızca size dönüş yapmak için kullanılır, ayrıntı için [KVKK metnine](/kvkk) bakın.",
    hata: "Adınızı ve geçerli bir telefon numarası yazın.",
    gonder: "WhatsApp ile gönder",
    epostaYaz: "E-posta yaz",
    msgTeklif: "Merhaba, toptan fiyat teklifi almak istiyorum.",
    msgBayi: "Merhaba, bayilik başvurusu yapmak istiyorum.",
    msgAd: "Ad Soyad",
    msgFirma: "Firma",
    msgSehir: "Şehir",
    msgIsletme: "İşletme türü",
    msgTelefon: "Telefon",
    msgMesaj: "Mesaj",
  },

  yasal: {
    ust: "Yasal",
    guncelleme: "Son güncelleme",
    tarih: "Ekim 2026",
    not: "",
    kvkk: {
      baslik: "KVKK Aydınlatma Metni",
      blok: [
        ["p", "6698 sayılı Kişisel Verilerin Korunması Kanunu'nun 10. maddesi gereği, kişisel verilerinizin nasıl işlendiğini bu metinle bildiriyoruz."],
        ["h", "Veri sorumlusu"],
        ["p", "{unvan}, {adres}. E-posta: {eposta}"],
        ["h", "Hangi verileri alıyoruz"],
        ["p", "İletişim ve bayilik formlarında yazdığınız ad soyad, telefon numarası, firma adı, şehir, işletme türü ve mesajınız. Bunun dışında sitede sizi tanımlayan bir veri toplamıyoruz."],
        ["h", "Ne için kullanıyoruz"],
        ["p", "Fiyat teklifi vermek, bayilik başvurunuzu değerlendirmek, sorularınızı yanıtlamak ve sipariş sürecini yürütmek için. Verileriniz pazarlama listesine eklenmez."],
        ["h", "Hukuki sebep"],
        ["p", "Talebinizin karşılanması için verinin işlenmesinin gerekli olması ve bir sözleşmenin kurulması için ön görüşme yapılması (KVKK m.5/2-c), ayrıca meşru menfaatimiz (m.5/2-f)."],
        ["h", "Kimlere aktarıyoruz"],
        ["p", "Formlar mesajınızı WhatsApp'a hazır olarak açar; mesajı göndermeniz halinde içerik WhatsApp altyapısı üzerinden bize ulaşır. E-posta ile yazarsanız mesajınız e-posta sağlayıcımızda tutulur. Yasal zorunluluk dışında üçüncü kişilerle paylaşmıyoruz."],
        ["h", "Ne kadar saklıyoruz"],
        ["p", "Görüşme sona erdikten sonra yasal saklama süreleri dolana kadar, bu süreler sonunda silinir ya da anonim hale getirilir."],
        ["h", "Haklarınız"],
        ["p", "KVKK m.11 uyarınca verilerinizin işlenip işlenmediğini öğrenme, işlenmişse bilgi talep etme, amacına uygun kullanılıp kullanılmadığını öğrenme, eksik veya yanlışsa düzeltilmesini, şartları oluşmuşsa silinmesini veya yok edilmesini isteme ve kanuna aykırı işleme nedeniyle zarar görürseniz zararın giderilmesini talep etme hakkına sahipsiniz."],
        ["p", "Başvurularınızı {eposta} adresine yazabilirsiniz; en geç 30 gün içinde cevap veririz."],
      ],
    },
    gizlilik: {
      baslik: "Gizlilik Politikası",
      blok: [
        ["p", "Bu site {ad} ürünlerini tanıtmak ve toptan taleplerini almak için hazırlandı. Ziyaretçilerimizin mahremiyetine saygı duyuyoruz."],
        ["h", "Topladığımız bilgiler"],
        ["p", "Sitede üyelik, sepet ya da online ödeme yok. Yalnızca siz formu doldurup gönderirseniz yazdığınız bilgileri alıyoruz. Bu bilgilerin nasıl işlendiği [KVKK aydınlatma metninde](/kvkk) anlatılıyor."],
        ["h", "Takip ve reklam"],
        ["p", "Sitede reklam ya da kullanıcı takibi yapan bir araç kullanmıyoruz. İleride ziyaretçi istatistiği için bir analiz aracı eklersek bu sayfayı ve [çerez politikasını](/cerez-politikasi) güncelleriz."],
        ["h", "Üçüncü taraf servisler"],
        ["p", "İletişim sayfasında Google Haritalar gömülüdür; harita yüklendiğinde Google kendi politikasına göre veri işleyebilir. WhatsApp ve sosyal medya bağlantılarına tıkladığınızda ilgili platformun kuralları geçerlidir."],
        ["h", "İletişim"],
        ["p", "Sorularınız için {eposta} adresine yazabilirsiniz."],
      ],
    },
    cerez: {
      baslik: "Çerez Politikası",
      blok: [
        ["p", "Bu sitenin kendi koyduğu bir çerez yok: oturum, analiz ya da reklam çerezi kullanmıyoruz, bu yüzden ayrıca onay penceresi de göstermiyoruz."],
        ["h", "İstisna: gömülü harita"],
        ["p", "İletişim sayfasındaki Google Haritalar bileşeni yüklendiğinde Google kendi çerezlerini bırakabilir. Bunu istemiyorsanız tarayıcınızdan üçüncü taraf çerezlerini engelleyebilir veya o sayfayı açmadan telefon ve e-posta ile ulaşabilirsiniz."],
        ["h", "İleride"],
        ["p", "Ziyaretçi sayısı ölçmek gibi amaçlarla çerez kullanan bir araç eklersek, önce size onay soracağız ve bu sayfayı güncelleyeceğiz."],
      ],
    },
  },

  bulunamadi: {
    baslik: "Bu sayfayı bulamadık",
    yazi: "Adres değişmiş ya da yanlış yazılmış olabilir.",
    ana: "Anasayfaya dön",
    urunler: "Ürünlere bak",
  },
};

export default tr;
